// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/LTSpark/Country-App/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CountryRepo is an autogenerated mock type for the CountryRepo type
type CountryRepo struct {
	mock.Mock
}

// GetAllCountries provides a mock function with given fields:
func (_m *CountryRepo) GetAllCountries() ([]domain.Country, error) {
	ret := _m.Called()

	var r0 []domain.Country
	if rf, ok := ret.Get(0).(func() []domain.Country); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Country)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCountries provides a mock function with given fields: params
func (_m *CountryRepo) GetCountries(params domain.Params) ([]domain.Country, error) {
	ret := _m.Called(params)

	var r0 []domain.Country
	if rf, ok := ret.Get(0).(func(domain.Params) []domain.Country); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Country)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
