// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/LTSpark/Country-App/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// WriteCountryRepo is an autogenerated mock type for the WriteCountryRepo type
type WriteCountryRepo struct {
	mock.Mock
}

// StoreAllCountriesList provides a mock function with given fields: c, fileName
func (_m *WriteCountryRepo) StoreAllCountriesList(c []domain.Country, fileName string) error {
	ret := _m.Called(c, fileName)

	var r0 error
	if rf, ok := ret.Get(0).(func([]domain.Country, string) error); ok {
		r0 = rf(c, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreCountryList provides a mock function with given fields: c, fileName
func (_m *WriteCountryRepo) StoreCountryList(c []domain.Country, fileName string) error {
	ret := _m.Called(c, fileName)

	var r0 error
	if rf, ok := ret.Get(0).(func([]domain.Country, string) error); ok {
		r0 = rf(c, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
